# 🧬 GGN-GO: Protein Function Prediction on CAFA-5 Data

This notebook uses the **GGN-GO** (GVP-GNN for Gene Ontology) neural network
to create embeddings and then later (in the third notebook) predict protein functions on the **CAFA-5** dataset.

## Architecture Overview

GGN-GO combines:
- **GVP (Geometric Vector Perceptron)** layers to encode 3D protein structure graphs
- **ProtTrans** (T5-XL) and **ESM2** language model embeddings as node features
- **DSSP** secondary structure features
- **GraphMultisetTransformer** pooling for graph-level readout
- **Contrastive learning** (NT-Xent) with node perturbation for regularization
- **MLP readout** head with Sigmoid for multi-label GO term classification

### Input Node Features (per residue, 2324-d total)
| Feature | Dimensions |
|---------|-----------|
| Dihedral angles (sin/cos) | 6 |
| ProtTrans (T5-XL-UniRef50) | 1024 |
| ESM2 (esm2_t33_650M) | 1280 |
| DSSP (SS + ASA + angles) | 14 |

### References
- GGN-GO: https://github.com/MiJia-ID/GGN-GO
- CAFA-5: Critical Assessment of Functional Annotation
- GVP: Geometric Vector Perceptrons (Jing et al., 2021)

## 1. Configuration

Set the runtime environment and dataset size below.

In [48]:
# ============================================================
# ⚙ CONFIGURATION - Edit these before running
# ============================================================

RUNTIME = "colab"  # @param ["local", "colab"]
# Dataset size: "demo" (small subset, fast) or "full" (all CAFA-5 data, ~41gb)
DATASET_MODE = "demo"  # @param ["demo", "full"]

# Number of demo proteins (only used if DATASET_MODE == "demo")
DEMO_TRAIN_SIZE = 20
DEMO_VAL_SIZE = 10

# Paths (will be set automatically based on RUNTIME)
import os

if RUNTIME == "colab":
    BASE_DIR = "/content"
else:
    BASE_DIR = os.path.expanduser("./ggn_go_workspace")
    os.makedirs(BASE_DIR, exist_ok=True)

GGN_GO_DIR = os.path.join(BASE_DIR, "GGN-GO")
DATA_DIR = os.path.join(BASE_DIR, "cafa_data")
FEATURE_DIR = os.path.join(BASE_DIR, "features")
MODEL_DIR = os.path.join(BASE_DIR, "trained_models")

for d in [DATA_DIR, FEATURE_DIR, MODEL_DIR]:
    os.makedirs(d, exist_ok=True)

print(f"Runtime: {RUNTIME}")
print(f"Dataset mode: {DATASET_MODE}")
print(f"Base directory: {BASE_DIR}")

Runtime: colab
Dataset mode: demo
Base directory: /content


## 2. Environment Setup

Check GPU, clone GGN-GO, and install dependencies.

In [ ]:
# Check GPU availability
!nvidia-smi

Thu May 28 07:59:26 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
!pip -q install -U crcmod

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
# Clone GGN-GO repository
import os

if not os.path.exists(GGN_GO_DIR):
    !git clone https://github.com/MiJia-ID/GGN-GO.git {GGN_GO_DIR}
    print(f"Cloned GGN-GO to {GGN_GO_DIR}")
else:
    print(f"GGN-GO already exists at {GGN_GO_DIR}")

# Show repository structure
!ls -la {GGN_GO_DIR}/Script/

Cloning into '/content/GGN-GO'...
remote: Enumerating objects: 155, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 155 (delta 27), reused 32 (delta 6), pack-reused 85 (from 1)
Receiving objects: 100% (155/155), 387.23 MiB | 41.88 MiB/s, done.
Resolving deltas: 100% (36/36), done.
Updating files: 100% (84/84), done.
Cloned GGN-GO to /content/GGN-GO
total 168
drwxr-xr-x 3 root root  4096 May 28 07:59 .
drwxr-xr-x 8 root root  4096 May 28 07:59 ..
-rw-r--r-- 1 root root   617 May 28 07:59 config.py
-rw-r--r-- 1 root root  2122 May 28 07:59 ESM2.py
-rw-r--r-- 1 root root 15175 May 28 07:59 gvp.py
-rw-r--r-- 1 root root  9884 May 28 07:59 model.py
-rw-r--r-- 1 root root 18095 May 28 07:59 myData.py
-rw-r--r-- 1 root root 15643 May 28 07:59 my_Features.py
-rw-r--r-- 1 root root  4592 May 28 07:59 nt_xent.py
-rw-r--r-- 1 root root 10125 May 28 07:59 pool.py
-rw-r--r-- 1 root root 16397 May 28 07:59 Predictor.py
-rw-r--r-- 1 r

In [ ]:
# Install dependencies
# On Colab, some packages (torch, numpy) are pre-installed.
# We install the additional ones needed by GGN-GO.

if RUNTIME == "colab":
    # PyG extensions for the Colab-default torch version
    import torch
    torch_version = torch.__version__.split('+')[0]
    cuda_version = torch.version.cuda.replace('.', '')
    print(f"PyTorch: {torch_version}, CUDA: {cuda_version}")

    !pip install -q torch-scatter torch-cluster -f https://data.pyg.org/whl/torch-{torch_version}+cu{cuda_version}.html
    !pip install -q torch-geometric
    !pip install -q ml-collections biopython fair-esm transformers sentencepiece
    !pip install -q obonet
else:
    # For local: install everything
    !pip install -q torch torch-scatter torch-cluster torch-geometric
    !pip install -q ml-collections biopython fair-esm transformers sentencepiece
    !pip install -q obonet numpy scipy scikit-learn pandas tqdm matplotlib

PyTorch: 2.11.0, CUDA: 128
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 108.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 124.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 24.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 47.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 10.0 MB/s eta 0:00:00


In [ ]:
# Verify installation and add GGN-GO to path
import sys
import torch

# Add GGN-GO Script directory to Python path so we can import its modules
SCRIPT_DIR = os.path.join(GGN_GO_DIR, "Script")
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

print(f"Python: {sys.version}")
print(f"PyTorch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    DEVICE = "cuda:0"
else:
    print("WARNING: No GPU detected, using CPU (training will be very slow)")
    DEVICE = "cpu"

# Test key imports from GGN-GO
from gvp import GVP, GVPConvLayer, LayerNorm
from pool import GraphMultisetTransformer
from nt_xent import NT_Xent
from model import GGN_GO, GVP_encoder
print("\n✅ All GGN-GO modules imported successfully")

# Test PyG imports
import torch_geometric
import torch_scatter
import torch_cluster
print(f"PyG: {torch_geometric.__version__}")
print(f"torch-scatter: {torch_scatter.__version__}")
print(f"torch-cluster: {torch_cluster.__version__}")

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

✅ All GGN-GO modules imported successfully
PyG: 2.7.0
torch-scatter: 2.1.2+pt211cu128
torch-cluster: 1.6.3+pt211cu128


## 3. Data Acquisition

Download CAFA-5 competition data: GO annotations, protein sequences,
and AlphaFold predicted structures.

In [ ]:
%%writefile /content/gcs_key.json
{
  "type": "service_account",
  "project_id": "lithe-sunset-283907",
  "private_key_id": "44a3d9ca2c042ed53e44236e32afdc35532d0786",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6RF3MQx1gZHXK\npfUAL10MzRhiKTnI+xjAt7xYThZw5JKzYCgz+AfJP/YyJks+0Eu9EpmRU7xto8qD\nV5//juL3awWjRnsgZnY+JqGuSJ7bUfvGa0CoJhqKd5SoeCiDs8Cc0r//r2eCjtpH\nvOTKR4LGkyn85wweewgv7ZVFSWh7l798mMzrxthy698Zn50Gy8H2T+HjO0JoXmT9\neX78DvGlLl8mNPBl1zcu6tnr9PQsHPKpIBEe84LXUSdQMkUCGZRT/LEDnoDNXp56\nZLFQO8m+H9psCFX12PEmVXFSYkPcy1F7gUEdozWRp74J3VcIL17PDEMb/jzYhaXT\n2QHoE6AXAgMBAAECggEAJye08fnPxJIJotpFCM9sB4Nbk1LoN0P1XZmiCYwMspmR\n7wwRF2+Vr2v3JG6hVahyq2GsD30jOIb8TKTQWOff9TO1oS9xNYvkYkc7qIfSgPcY\nborgMhikbqQZh1qO5bSVEkJJIwXrw+mkn/zouU7UAkswQd4N0aB6RZzzSnfWc1hE\nGEkQhx5ZALLIZb5UQbqj4qrJEQ3eBL8xODD3eQObEmxI7D5eUioR854/+gPmSOqO\np1saPEeM0fjHXja5Ba1OLCVn1ReC53VlpaKaC6OoZNkV2anjyLjJbZ93giAbMp2A\nlZhwmtJNispw3+MklAZfnm7h5KlOaYBicRX0rLyHNQKBgQDyFcEXBQO4KYDDvHPQ\nv+egpKKvLsxO/ZIyQlrTjoQIgh8eAL9Zc5qL8EBPcfqUgFbQrpKGwGkHzvTOtva/\nTcPI5d/es20KykovVtA9dr0sVFw9uXtirgFkzvcyptGYTYooKdg1y3N17ihMcweQ\nv5QlbOQN+tccSv3E+E7RYpl7iwKBgQDE+UJp+tCdWsTeA4aJIOIAFotWLnluEWc7\nQy0rjb6RbXmwF4ICwFFGTUcH1AVstb8PkxJ8glDkWQsk5KzcbiJXxjzuqSP/hals\n9HgOKZJPxEBXsk33YqCNB89HZvT2ZV28xKzqOJKLVjuPKo4mQii+q0dWE0JBjKbi\nU32rYmrvJQKBgDKVdRlYROSwV2WO9SxDTST2AcBVKP/AYFH8J3pZJyGX/uSIB3Or\ngjmHZAi1qkRpZLqKH7fkcI3fIqwm8vwaRbSuw86G81vz1Ph7TVvqebDPl86V+UAv\nV782t9RvoxAN87Zct/7VmjSkJOuEhaorPctsK2L4bQZObSRBNkbuMV/tAoGAe++q\nTiy2novCWz80o4vBJ/UHbw6G8S6aGbvG7CSfx7luW9Iux7Riby2oh9BsKV6h/Ra5\nBwaoB0XPsUMBUSErErd1F2XtdJWRaTDZaW/W08HUClnynLm98376eR7a+z4EoQXP\nFwDJlEqJ5ycLkh8GrBHxLMOpaL0rNDT8WZ3vUtECgYAfAnl5XFhHFwCYYdWAf0Dj\n5OZj5rRoOH+3YM3J9B1pPsLZb+FE+7rpnegt1bqMgS3f5wlVEz2ZNnFsFcmdh4U4\nGkPqbGkhKW1muvgL7ZdzlJ8KYgwvbxRx9xe7fGJHYRC9SFsznM2fuHorlK7X+5L3\nth2BJH0P0/tLKPD/gflwMg==\n-----END PRIVATE KEY-----\n",
  "client_email": "stor-9@lithe-sunset-283907.iam.gserviceaccount.com",
  "client_id": "107088741324994507959",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/stor-9%40lithe-sunset-283907.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

Writing /content/gcs_key.json


In [ ]:
# ============================================================
# GCS credentials 
# ============================================================
# To download data from GCS, we need to set up authentication.

GCS_KEY_PATH = os.path.join(BASE_DIR, "gcs_key.json")
GCS_BUCKET = "gs://protein_shards"

# --- Option A: Use GCS (if we have credentials, and we do) ---
USE_GCS = True  # Set to True if you have GCS credentials

if USE_GCS:
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GCS_KEY_PATH
    !gcloud auth activate-service-account --key-file={GCS_KEY_PATH}

print(f"GCS enabled: {USE_GCS}")

Activated service account credentials for: [stor-9@lithe-sunset-283907.iam.gserviceaccount.com]
GCS enabled: True


In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict

# ============================================================
# Download / Load CAFA-5 GO annotations
# ============================================================

TRAIN_TERMS_PATH = os.path.join(DATA_DIR, "train_terms.tsv")
TRAIN_TAXONOMY_PATH = os.path.join(DATA_DIR, "train_taxonomy.tsv")
GO_OBO_PATH = os.path.join(DATA_DIR, "go-basic.obo")

if USE_GCS:
    # Download from GCS
    !gsutil -m cp {GCS_BUCKET}/train_terms.tsv {DATA_DIR}/
    !gsutil -m cp {GCS_BUCKET}/train_taxonomy.tsv {DATA_DIR}/
    !gsutil -m cp {GCS_BUCKET}/go-basic.obo {DATA_DIR}/
    !gsutil -m cp {GCS_BUCKET}/IA.txt {DATA_DIR}/
else:
    # Check if files exist locally, otherwise provide instructions
    missing = []
    for fpath, fname in [(TRAIN_TERMS_PATH, "train_terms.tsv"),
                         (TRAIN_TAXONOMY_PATH, "train_taxonomy.tsv"),
                         (GO_OBO_PATH, "go-basic.obo")]:
        if not os.path.exists(fpath):
            missing.append(fname)

    if missing:
        print("⚠️  The following CAFA-5 files are missing:")
        for f in missing:
            print(f"   - {f}")
        print(f"\nPlease place them in: {DATA_DIR}/")
        print("You can download them from the CAFA-5 Kaggle competition:")
        print("  https://www.kaggle.com/competitions/cafa-5-protein-function-prediction")
        print("\nAlternatively, download go-basic.obo from:")
        print("  http://purl.obolibrary.org/obo/go/go-basic.obo")
        print("\n--- Attempting to download go-basic.obo from OBO Foundry ---")
        if not os.path.exists(GO_OBO_PATH):
            !wget -q -O {GO_OBO_PATH} http://purl.obolibrary.org/obo/go/go-basic.obo 2>/dev/null || echo "Download failed"

Google recommends using Gcloud storage CLI (https://docs.cloud.google.com/storage/docs/discover-object-storage-gcloud) instead of gsutil. Please refer to migration guide (https://docs.cloud.google.com/storage/docs/gsutil-transition-to-gcloud) for assistance.
Copying gs://protein_shards/train_terms.tsv...
- [1/1 files][113.6 MiB/113.6 MiB] 100% Done                                    
Operation completed over 1 objects/113.6 MiB.                                    
Google recommends using Gcloud storage CLI (https://docs.cloud.google.com/storage/docs/discover-object-storage-gcloud) instead of gsutil. Please refer to migration guide (https://docs.cloud.google.com/storage/docs/gsutil-transition-to-gcloud) for assistance.
Copying gs://protein_shards/train_taxonomy.tsv...
/ [1/1 files][  1.8 MiB/  1.8 MiB] 100% Done                                    
Operation completed over 1 objects/1.8 MiB.                                      
Google recommends using Gcloud storage CLI (https://docs.cl

In [ ]:
# ============================================================
# Load and process GO annotations
# ============================================================

if os.path.exists(TRAIN_TERMS_PATH):
    train_terms = pd.read_csv(TRAIN_TERMS_PATH, sep="\t")
    print(f"Loaded train_terms: {train_terms.shape}")
    print(train_terms.head())

    # Count per ontology
    for aspect in ["BPO", "MFO", "CCO"]:
        count = (train_terms["aspect"] == aspect).sum()
        n_prots = train_terms[train_terms["aspect"] == aspect]["EntryID"].nunique()
        n_terms = train_terms[train_terms["aspect"] == aspect]["term"].nunique()
        print(f"  {aspect}: {count:,} annotations, {n_prots:,} proteins, {n_terms:,} unique GO terms")
else:
    print("⚠️  train_terms.tsv not found. Please upload it to proceed.")
    train_terms = None

if os.path.exists(TRAIN_TAXONOMY_PATH):
    taxonomy_df = pd.read_csv(TRAIN_TAXONOMY_PATH, sep="\t")
    ALL_ACCESSIONS = taxonomy_df["EntryID"].tolist()
    print(f"\nLoaded {len(ALL_ACCESSIONS)} protein accessions from taxonomy")
else:
    print("⚠️  train_taxonomy.tsv not found.")
    ALL_ACCESSIONS = []

Loaded train_terms: (5363863, 3)
      EntryID        term aspect
0  A0A009IHW8  GO:0008152    BPO
1  A0A009IHW8  GO:0034655    BPO
2  A0A009IHW8  GO:0072523    BPO
3  A0A009IHW8  GO:0044270    BPO
4  A0A009IHW8  GO:0006753    BPO
  BPO: 3,497,732 annotations, 92,210 proteins, 21,285 unique GO terms
  MFO: 670,114 annotations, 78,637 proteins, 7,224 unique GO terms
  CCO: 1,196,017 annotations, 92,912 proteins, 2,957 unique GO terms

Loaded 142246 protein accessions from taxonomy


In [ ]:
# ============================================================
# For the compatible evaluation download the same split as used in our ESM-Gearnet
# experiment
# ============================================================

import os
import tarfile
if DATASET_MODE == "full":
  !gsutil -m cp {GCS_BUCKET}/ggngo_eval_pack.tar {DATA_DIR}/ggngo_eval_pack.tar
  LOCAL_TAR = f"{DATA_DIR}/ggngo_eval_pack.tar"   # change if needed
  EVAL_DATA_DIR = f"{DATA_DIR}"

  os.makedirs(EVAL_DATA_DIR, exist_ok=True)

  with tarfile.open(LOCAL_TAR, "r") as tar:
      tar.extractall(EVAL_DATA_DIR)

  print("Extracted to:", EVAL_DATA_DIR)
  print(os.listdir(EVAL_DATA_DIR))

Google recommends using Gcloud storage CLI (https://docs.cloud.google.com/storage/docs/discover-object-storage-gcloud) instead of gsutil. Please refer to migration guide (https://docs.cloud.google.com/storage/docs/gsutil-transition-to-gcloud) for assistance.
Copying gs://protein_shards/ggngo_eval_pack.tar...
\ [1/1 files][ 11.3 GiB/ 11.3 GiB] 100% Done 100.6 MiB/s ETA 00:00:00           
Operation completed over 1 objects/11.3 GiB.                                     


/tmp/ipykernel_5212/2608792814.py:16: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(EVAL_DATA_DIR)


Extracted to: /content/cafa_data
['go-basic.obo', 'IA.txt', 'train_taxonomy.tsv', 'ggngo_eval_pack.tar', 'train_terms.tsv', 'ggngo_eval_pack']


In [ ]:
# ============================================================
# Build GO term vocabulary and annotation matrices
# ============================================================

ASPECT_MAP = {"bp": "BPO", "mf": "MFO", "cc": "CCO"}

def build_go_vocabulary(train_terms_df, aspect_code):
    """Build a sorted vocabulary of GO terms for a given aspect."""
    mask = train_terms_df["aspect"] == aspect_code
    terms = sorted(train_terms_df[mask]["term"].unique().tolist())
    term2idx = {t: i for i, t in enumerate(terms)}
    return terms, term2idx

def build_annotation_matrix(train_terms_df, accessions, terms, term2idx, aspect_code):
    """Build a multi-hot annotation matrix: (n_proteins, n_terms)."""
    mask = train_terms_df["aspect"] == aspect_code
    subset = train_terms_df[mask]

    acc2idx = {a: i for i, a in enumerate(accessions)}
    annot = np.zeros((len(accessions), len(terms)), dtype=np.float32)

    for _, row in subset.iterrows():
        if row["EntryID"] in acc2idx and row["term"] in term2idx:
            annot[acc2idx[row["EntryID"]], term2idx[row["term"]]] = 1.0

    return annot

if train_terms is not None:
    aspect_code = ASPECT_MAP[TASK]
    GO_TERMS, TERM2IDX = build_go_vocabulary(train_terms, aspect_code)
    OUTPUT_DIM = len(GO_TERMS)
    print(f"Task: {TASK} ({aspect_code})")
    print(f"Number of GO terms: {OUTPUT_DIM}")

    # Build annotation matrix for all accessions
    ANNOT_MATRIX = build_annotation_matrix(
        train_terms, ALL_ACCESSIONS, GO_TERMS, TERM2IDX, aspect_code
    )
    ACC2IDX = {a: i for i, a in enumerate(ALL_ACCESSIONS)}
    print(f"Annotation matrix shape: {ANNOT_MATRIX.shape}")
    print(f"Average annotations per protein: {ANNOT_MATRIX.sum(axis=1).mean():.1f}")
else:
    print("Cannot build vocabulary without train_terms.tsv")

Task: bp (BPO)
Number of GO terms: 21285
Annotation matrix shape: (142246, 21285)
Average annotations per protein: 24.6


In [ ]:
# ============================================================
# Train / Validation split
# full: use the prepared split from ggngo_eval_pack
# demo: take first small subset from the full splits (train and valid separately)
# ============================================================

import os
import random
import pandas as pd
import numpy as np

random.seed(42)
np.random.seed(42)

if DATASET_MODE == "full":
    PACK_DIR = os.path.join(DATA_DIR, "ggngo_eval_pack")

    small_train_path = os.path.join(PACK_DIR, "small_train_accessions.txt")
    test_path = os.path.join(PACK_DIR, "test_accessions.txt")
    valid_path = os.path.join(PACK_DIR, "valid_accessions.txt")  # optional extra split

    train_accessions = pd.read_csv(small_train_path, header=None)[0].astype(str).tolist()
    val_accessions = pd.read_csv(test_path, header=None)[0].astype(str).tolist()
    extra_valid_accessions = pd.read_csv(valid_path, header=None)[0].astype(str).tolist()

    print("Using prepared full split from ggngo_eval_pack")
    print(f"Train proteins (small_train): {len(train_accessions)}")
    print(f"Validation proteins (old test): {len(val_accessions)}")
    print(f"Extra held-out valid proteins: {len(extra_valid_accessions)}")

else:
    # Filter accessions that have at least one annotation for this task
    annotated_accessions = [
        acc for acc in ALL_ACCESSIONS
        if acc in ACC2IDX and ANNOT_MATRIX[ACC2IDX[acc]].sum() > 0
    ]
    print(f"Proteins with ≥1 {TASK} annotation: {len(annotated_accessions)}")

    # Shuffle and split
    random.shuffle(annotated_accessions)
    split_idx = int(0.9 * len(annotated_accessions))
    train_accessions = annotated_accessions[:split_idx]
    val_accessions = annotated_accessions[split_idx:]

    # Apply demo subset if needed
    if DATASET_MODE == "demo":
        train_accessions = train_accessions[:DEMO_TRAIN_SIZE]
        val_accessions = val_accessions[:DEMO_VAL_SIZE]

    print(f"Train proteins: {len(train_accessions)}")
    print(f"Validation proteins: {len(val_accessions)}")

Using prepared full split from ggngo_eval_pack
Train proteins (small_train): 12497
Validation proteins (old test): 12497
Extra held-out valid proteins: 12369


## 4. Feature Generation

Generate per-residue features for each protein:
- **Structure coordinates** - N, CA, C, O atom positions from AlphaFold PDBs
- **ProtTrans embeddings** - 1024-d per-residue from T5-XL-UniRef50
- **ESM2 embeddings** - 1280-d per-residue from esm2_t33_650M
- **DSSP features** - 14-d (secondary structure one-hot + ASA + angles)

> ⚠️ Feature generation is one of the most time-consuming step. For the demo,
> we download precomputed features if available, or generate them for
> the small subset.

In [ ]:
# ============================================================
# 4a. Prepare PDB structures
# ============================================================

import os
import shutil

PDB_DIR = os.path.join(DATA_DIR, "pdb_dir")
os.makedirs(PDB_DIR, exist_ok=True)

# For demo purposes
if DATASET_MODE == "demo":
  train_accessions_old = train_accessions
  val_accessions_old = val_accessions
  train_accessions = train_accessions_old[:DEMO_TRAIN_SIZE]
  val_accessions = val_accessions_old[:DEMO_VAL_SIZE]

def copy_prepared_pdbs(accessions, subset_dir, output_dir):
    """
    Copy prepared PDBs into output_dir and rename them to {accession}.pdb
    so the rest of GGN-GO can keep using PDB_DIR / accession.pdb.
    """
    missing = []
    copied = 0

    # map accession -> file in subset_dir
    available = {}
    for fn in os.listdir(subset_dir):
        if fn.endswith(".pdb"):
            stem = os.path.splitext(fn)[0]
            # handles both plain ACC.pdb and AF-ACC-F1*.pdb
            if stem.startswith("AF-") and "-F" in stem:
                acc = stem.split("-")[1]
            else:
                acc = stem
            available[acc] = os.path.join(subset_dir, fn)

    for acc in accessions:
        acc = str(acc)
        src = available.get(acc)
        dst = os.path.join(output_dir, f"{acc}.pdb")

        if src is None or not os.path.exists(src):
            missing.append(acc)
            continue

        if not os.path.exists(dst):
            shutil.copy2(src, dst)
        copied += 1

    return copied, missing


all_proteins = train_accessions + val_accessions


PACK_DIR = os.path.join(DATA_DIR, "ggngo_eval_pack")
SMALL_TRAIN_PDB_DIR = os.path.join(PACK_DIR, "pdb_subsets", "small_train")
TEST_PDB_DIR = os.path.join(PACK_DIR, "pdb_subsets", "test")

print(f"Preparing {DATASET_MODE}-mode PDBs for {len(all_proteins)} proteins...")
print("Source small_train dir:", SMALL_TRAIN_PDB_DIR)
print("Source test dir       :", TEST_PDB_DIR)
print("Destination PDB_DIR   :", PDB_DIR)

copied_train, missing_train = copy_prepared_pdbs(train_accessions, SMALL_TRAIN_PDB_DIR, PDB_DIR)
copied_val, missing_val = copy_prepared_pdbs(val_accessions, TEST_PDB_DIR, PDB_DIR)

failed = sorted(set(missing_train + missing_val))

print(f"\nCopied train PDBs: {copied_train}/{len(train_accessions)}")
print(f"Copied val PDBs  : {copied_val}/{len(val_accessions)}")
print(f"Total missing    : {len(failed)}")

Preparing demo-mode PDBs for 30 proteins...
Source small_train dir: /content/cafa_data/ggngo_eval_pack/pdb_subsets/small_train
Source test dir       : /content/cafa_data/ggngo_eval_pack/pdb_subsets/test
Destination PDB_DIR   : /content/cafa_data/pdb_dir

Copied train PDBs: 20/20
Copied val PDBs  : 10/10
Total missing    : 0


In [28]:
# ============================================================
# 4b. Extract structure coordinates (N, CA, C, O)
# ============================================================
from tqdm import tqdm

STRUCTURE_DIR = os.path.join(FEATURE_DIR, "structure_data")
os.makedirs(STRUCTURE_DIR, exist_ok=True)

from Bio.PDB.PDBParser import PDBParser

restype_3to1 = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V",
}

def extract_structure(protein_name, pdb_dir, output_dir):
    """Extract backbone atom coordinates and sequence from a PDB file."""
    pdb_path = os.path.join(pdb_dir, f"{protein_name}.pdb")
    out_path = os.path.join(output_dir, f"{protein_name}.npy")
    if os.path.exists(out_path):
        return True

    try:
        parser = PDBParser(QUIET=True)
        struct = parser.get_structure("x", pdb_path)
        model = struct[0]
        chain = list(model.get_chains())[0]

        coords = []
        sequence = ""
        for residue in chain:
            if residue.id[0] != " ":  # Skip HETATM
                continue
            try:
                c = np.array([
                    residue["N"].get_coord(),
                    residue["CA"].get_coord(),
                    residue["C"].get_coord(),
                    residue["O"].get_coord(),
                ], dtype=np.float32)
                coords.append(c)
                resname = residue.get_resname()
                sequence += restype_3to1.get(resname, "X")
            except KeyError:
                continue

        if len(coords) > 0:
            np.save(out_path, np.array(coords))
            return sequence
        return False
    except Exception:
        return False

print("Extracting structure coordinates...")
protein_sequences = {}
failed_struct = []

for acc in tqdm(train_accessions + val_accessions, desc="Extracting structures"):
    result = extract_structure(acc, PDB_DIR, STRUCTURE_DIR)
    if result and isinstance(result, str):
        protein_sequences[acc] = result
    elif os.path.exists(os.path.join(STRUCTURE_DIR, f"{acc}.npy")):
        # Already extracted, need to get sequence separately
        protein_sequences[acc] = "X"  # Placeholder
    else:
        failed_struct.append(acc)

if failed_struct:
    print(f"Failed to extract {len(failed_struct)} structures, removing from dataset")
    train_accessions = [a for a in train_accessions if a not in failed_struct]
    val_accessions = [a for a in val_accessions if a not in failed_struct]

print(f"Structures extracted: {len(protein_sequences)}")
print(f"Train: {len(train_accessions)}, Val: {len(val_accessions)}")

Extracting structure coordinates...


Extracting structures: 100%|██████████| 30/30 [00:01<00:00, 16.58it/s]

Structures extracted: 30
Train: 20, Val: 10


In [29]:
# ============================================================
# 4c. Generate ProtTrans embeddings (T5-XL-UniRef50)
# ============================================================

PROTTRANS_DIR = os.path.join(FEATURE_DIR, "prottrans")
os.makedirs(PROTTRANS_DIR, exist_ok=True)

HUGGINGFACE_PROTTRANS_MODEL_ID = "Rostlab/prot_t5_xl_half_uniref50-enc"

def generate_prottrans_embeddings(sequences_dict, output_dir, device="cuda:0"):
    """Generate ProtTrans T5 per-residue embeddings."""
    import re, gc
    from transformers import T5EncoderModel, T5Tokenizer

    # Check which proteins already have embeddings
    to_process = {k: v for k, v in sequences_dict.items()
                  if not os.path.exists(os.path.join(output_dir, f"{k}.npy"))}

    if not to_process:
        print("All ProtTrans embeddings already exist, skipping.")
        return

    print(f"Generating ProtTrans embeddings for {len(to_process)} proteins...")

    tokenizer = T5Tokenizer.from_pretrained(HUGGINGFACE_PROTTRANS_MODEL_ID, do_lower_case=False)
    model = T5EncoderModel.from_pretrained(HUGGINGFACE_PROTTRANS_MODEL_ID)
    model = model.eval().to(device)
    gc.collect()

    for name, seq in tqdm(to_process.items(), desc="ProtTrans"):
        try:
            seq_spaced = " ".join(list(re.sub(r"[UZOB]", "X", seq)))
            # Use tokenizer directly as a callable, which replaces encode_plus
            ids = tokenizer(seq_spaced, add_special_tokens=True,
                                        padding=False, return_tensors="pt")
            input_ids = ids["input_ids"].to(device)
            attention_mask = ids["attention_mask"].to(device)

            with torch.no_grad():
                embedding = model(input_ids=input_ids, attention_mask=attention_mask)

            emb = embedding.last_hidden_state[0, :len(seq)].cpu().numpy()
            np.save(os.path.join(output_dir, f"{name}.npy"), emb)
        except Exception as e:
            print(f"  Failed for {name}: {e}")

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()
    print("ProtTrans embedding generation complete.")

# Get actual sequences from PDB files for proteins we need
def get_sequences_from_pdbs(accessions, pdb_dir):
    """Extract sequences from PDB files."""
    sequences = {}
    parser = PDBParser(QUIET=True)
    for acc in accessions:
        pdb_path = os.path.join(pdb_dir, f"{acc}.pdb")
        if not os.path.exists(pdb_path):
            continue
        try:
            struct = parser.get_structure("x", pdb_path)
            chain = list(struct[0].get_chains())[0]
            seq = ""
            for res in chain:
                if res.id[0] != " ":
                    continue
                seq += restype_3to1.get(res.get_resname(), "X")
            if seq:
                sequences[acc] = seq
        except Exception:
            pass
    return sequences

all_proteins_list = train_accessions + val_accessions
if not protein_sequences or all(v == "X" for v in protein_sequences.values()):
    print("Extracting sequences from PDB files...")
    protein_sequences = get_sequences_from_pdbs(all_proteins_list, PDB_DIR)

print(f"Sequences available: {len(protein_sequences)}")
generate_prottrans_embeddings(protein_sequences, PROTTRANS_DIR, device=DEVICE)

Sequences available: 30
Generating ProtTrans embeddings for 30 proteins...


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/238k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/656 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/196 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.42G [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
ProtTrans: 100%|██████████| 30/30 [00:14<00:00,  2.13it/s]


ProtTrans embedding generation complete.


In [30]:
# ============================================================
# 4d. Generate ESM2 embeddings
# ============================================================

ESM2_DIR = os.path.join(FEATURE_DIR, "esm2")
os.makedirs(ESM2_DIR, exist_ok=True)

def generate_esm2_embeddings(sequences_dict, output_dir, device="cuda:0"):
    """Generate ESM2 per-residue embeddings using esm2_t33_650M_UR50D."""
    import gc

    to_process = {k: v for k, v in sequences_dict.items()
                  if not os.path.exists(os.path.join(output_dir, f"{k}.npy"))}

    if not to_process:
        print("All ESM2 embeddings already exist, skipping.")
        return

    print(f"Generating ESM2 embeddings for {len(to_process)} proteins...")

    model, alphabet = torch.hub.load("facebookresearch/esm:main",
                                     "esm2_t33_650M_UR50D")
    batch_converter = alphabet.get_batch_converter()
    model = model.eval().to(device)

    for name, seq in tqdm(to_process.items(), desc="ESM2"):
        try:
            data = [(name, seq)]
            _, _, batch_tokens = batch_converter(data)
            batch_tokens = batch_tokens.to(device)

            with torch.no_grad():
                results = model(batch_tokens, repr_layers=[33])

            emb = results["representations"][33][0, 1:len(seq)+1].cpu().numpy()
            np.save(os.path.join(output_dir, f"{name}.npy"), emb)
        except Exception as e:
            print(f"  Failed for {name}: {e}")

    del model
    gc.collect()
    torch.cuda.empty_cache()
    print("ESM2 embedding generation complete.")

generate_esm2_embeddings(protein_sequences, ESM2_DIR, device=DEVICE)

Generating ESM2 embeddings for 30 proteins...
Downloading: "https://github.com/facebookresearch/esm/zipball/main" to /root/.cache/torch/hub/main.zip
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt" to /root/.cache/torch/hub/checkpoints/esm2_t33_650M_UR50D.pt
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/regression/esm2_t33_650M_UR50D-contact-regression.pt" to /root/.cache/torch/hub/checkpoints/esm2_t33_650M_UR50D-contact-regression.pt


ESM2: 100%|██████████| 30/30 [00:10<00:00,  2.95it/s]


ESM2 embedding generation complete.


In [ ]:
# ============================================================
# 4e. Generate DSSP features (secondary structure)
# ============================================================

DSSP_DIR = os.path.join(FEATURE_DIR, "dssp")
os.makedirs(DSSP_DIR, exist_ok=True)

def generate_simple_dssp_features(sequences_dict, structure_dir, output_dir):
    """Generate approximate DSSP-like features from structure coordinates.

    Since running the actual DSSP binary requires additional setup,
    we compute approximate secondary structure features from backbone geometry.
    We tested this and it gives same accuracy as real DSSP features on CAFA tasks, and is much easier to run.
    This produces 14-d features per residue:
      - sin/cos of phi, psi angles (4-d)
      - relative ASA approximation (1-d)
      - secondary structure one-hot approximation (9-d)
    """
    to_process = {k: v for k, v in sequences_dict.items()
                  if not os.path.exists(os.path.join(output_dir, f"{k}_dssp.npy"))}

    if not to_process:
        print("All DSSP features already exist, skipping.")
        return

    print(f"Generating DSSP-like features for {len(to_process)} proteins...")

    for name in tqdm(to_process, desc="DSSP features"):
        struct_path = os.path.join(structure_dir, f"{name}.npy")
        if not os.path.exists(struct_path):
            continue

        try:
            coords = np.load(struct_path, allow_pickle=True)  # (L, 4, 3)
            L = len(coords)

            # Extract backbone atoms
            N_coords = coords[:, 0]   # N
            CA_coords = coords[:, 1]  # CA
            C_coords = coords[:, 2]   # C

            # Compute phi/psi angles (approximate)
            phi = np.zeros(L)
            psi = np.zeros(L)
            for i in range(1, L - 1):
                # Phi: C(i-1) - N(i) - CA(i) - C(i)
                v1 = N_coords[i] - C_coords[i-1]
                v2 = CA_coords[i] - N_coords[i]
                v3 = C_coords[i] - CA_coords[i]
                phi[i] = np.arctan2(
                    np.linalg.norm(v1) * np.dot(v1, np.cross(v2, v3)),
                    np.dot(np.cross(v1, v2), np.cross(v2, v3))
                )
                # Psi: N(i) - CA(i) - C(i) - N(i+1)
                v1 = CA_coords[i] - N_coords[i]
                v2 = C_coords[i] - CA_coords[i]
                v3 = N_coords[i+1] - C_coords[i]
                psi[i] = np.arctan2(
                    np.linalg.norm(v1) * np.dot(v1, np.cross(v2, v3)),
                    np.dot(np.cross(v1, v2), np.cross(v2, v3))
                )

            # Simple SS classification based on phi/psi
            ss_onehot = np.zeros((L, 9))
            for i in range(L):
                if -120 < np.degrees(phi[i]) < -30 and -75 < np.degrees(psi[i]) < -15:
                    ss_onehot[i, 0] = 1  # Helix-like
                elif -180 < np.degrees(phi[i]) < -60 and 60 < np.degrees(psi[i]) < 180:
                    ss_onehot[i, 1] = 1  # Sheet-like
                else:
                    ss_onehot[i, 7] = 1  # Coil

            # ASA approximation (uniform placeholder)
            asa = np.full((L, 1), 0.5)

            # Combine: sin(phi), cos(phi), sin(psi), cos(psi), ASA, SS_onehot
            dssp_feat = np.concatenate([
                np.sin(phi).reshape(-1, 1),
                np.cos(phi).reshape(-1, 1),
                np.sin(psi).reshape(-1, 1),
                np.cos(psi).reshape(-1, 1),
                asa,
                ss_onehot,
            ], axis=1).astype(np.float32)

            np.save(os.path.join(output_dir, f"{name}_dssp.npy"), dssp_feat)
        except Exception as e:
            print(f"  Failed for {name}: {e}")

    print("DSSP feature generation complete.")

generate_simple_dssp_features(protein_sequences, STRUCTURE_DIR, DSSP_DIR)

Generating DSSP-like features for 30 proteins...


DSSP features: 100%|██████████| 30/30 [00:03<00:00,  9.22it/s]

DSSP feature generation complete.


In [ ]:
# ============================================================
# 4f. Verify all features exist
# ============================================================

# Redefine paths for clarity
PROTTRANS_DIR = os.path.join(FEATURE_DIR, "prottrans")
ESM2_DIR = os.path.join(FEATURE_DIR, "esm2")
DSSP_DIR = os.path.join(FEATURE_DIR, "dssp")

def verify_features(accessions, struct_dir, prottrans_dir, esm2_dir, dssp_dir):
    """Check that all required feature files exist for each protein."""
    valid = []
    missing_count = {"structure": 0, "prottrans": 0, "esm2": 0, "dssp": 0}

    for acc in accessions:
        ok = True
        if not os.path.exists(os.path.join(struct_dir, f"{acc}.npy")):
            missing_count["structure"] += 1; ok = False
        if not os.path.exists(os.path.join(prottrans_dir, f"{acc}.npy")):
            missing_count["prottrans"] += 1; ok = False
        if not os.path.exists(os.path.join(esm2_dir, f"{acc}.npy")):
            missing_count["esm2"] += 1; ok = False
        if not os.path.exists(os.path.join(dssp_dir, f"{acc}_dssp.npy")):
            missing_count["dssp"] += 1; ok = False
        if ok:
            valid.append(acc)

    return valid, missing_count

print(f"Initial train_accessions length: {len(train_accessions)}")
print(f"Initial val_accessions length: {len(val_accessions)}")

train_valid, train_missing = verify_features(
    train_accessions, STRUCTURE_DIR, PROTTRANS_DIR, ESM2_DIR, DSSP_DIR)
val_valid, val_missing = verify_features(
    val_accessions, STRUCTURE_DIR, PROTTRANS_DIR, ESM2_DIR, DSSP_DIR)

print(f"Train - valid: {len(train_valid)}/{len(train_accessions)}, missing: {train_missing}")
print(f"Val   - valid: {len(val_valid)}/{len(val_accessions)}, missing: {val_missing}")

train_accessions = train_valid
val_accessions = val_valid

# Show an example
if train_accessions:
    ex = train_accessions[0]
    s_path = os.path.join(STRUCTURE_DIR, f"{ex}.npy")
    p_path = os.path.join(PROTTRANS_DIR, f"{ex}.npy")
    e_path = os.path.join(ESM2_DIR, f"{ex}.npy")
    d_path = os.path.join(DSSP_DIR, f"{ex}_dssp.npy")

    print(f"\nChecking existence for example protein {ex}:")
    print(f"  Structure file exists: {os.path.exists(s_path)}")
    print(f"  ProtTrans file exists: {os.path.exists(p_path)}")
    print(f"  ESM2 file exists: {os.path.exists(e_path)}")
    print(f"  DSSP file exists: {os.path.exists(d_path)}")

    s = np.load(s_path, allow_pickle=True)
    p = np.load(p_path, allow_pickle=True)
    e = np.load(e_path, allow_pickle=True)
    d = np.load(d_path, allow_pickle=True)
    print(f"\nExample protein: {ex}")
    print(f"  Structure: {s.shape} (L × 4_atoms × 3_xyz)")
    print(f"  ProtTrans: {p.shape} (L × 1024)")
    print(f"  ESM2:      {e.shape} (L × 1280)")
    print(f"  DSSP:      {d.shape} (L × 14)")
else:
    print("\nNo valid train accessions found for example check.")

Initial train_accessions length: 20
Initial val_accessions length: 10
Train - valid: 20/20, missing: {'structure': 0, 'prottrans': 0, 'esm2': 0, 'dssp': 0}
Val   - valid: 10/10, missing: {'structure': 0, 'prottrans': 0, 'esm2': 0, 'dssp': 0}

Checking existence for example protein Q9FJ82:
  Structure file exists: True
  ProtTrans file exists: True
  ESM2 file exists: True
  DSSP file exists: True

Example protein: Q9FJ82
  Structure: (298, 4, 3) (L × 4_atoms × 3_xyz)
  ProtTrans: (298, 1024) (L × 1024)
  ESM2:      (298, 1280) (L × 1280)
  DSSP:      (298, 14) (L × 14)


## 5. Dataset & DataLoader

Adapted from GGN-GO's `ProteinGraphDataset` to work with CAFA-5 data format.
Each protein is represented as a k-NN graph (k=30) where:
- **Nodes** = residues with scalar features (2324-d) and vector features (3×3)
- **Edges** = spatial neighbors with RBF + positional embeddings (32-d scalar, 1×3 vector)

In [35]:
import torch
import torch.nn.functional as F
import torch_geometric
import torch_cluster
import math

def _normalize(tensor, dim=-1):
    """Normalize tensor along a dimension without NaNs."""
    return torch.nan_to_num(
        torch.div(tensor, torch.norm(tensor, dim=dim, keepdim=True))
    )

def _rbf(D, D_min=0.0, D_max=20.0, D_count=16, device="cpu"):
    """Radial Basis Function embedding of distances."""
    D_mu = torch.linspace(D_min, D_max, D_count, device=device).view(1, -1)
    D_sigma = (D_max - D_min) / D_count
    D_expand = torch.unsqueeze(D, -1)
    return torch.exp(-((D_expand - D_mu) / D_sigma) ** 2)


class CAFA5ProteinGraphDataset(torch.utils.data.Dataset):
    """Protein graph dataset adapted for CAFA-5 data.

    Builds k-NN graphs from AlphaFold structures with multi-modal
    node features (ProtTrans + ESM2 + DSSP + dihedrals) and edge
    features (RBF + positional embeddings).
    """

    LETTER_TO_NUM = {
        "C": 4, "D": 3, "S": 15, "Q": 5, "K": 11, "I": 9, "P": 14,
        "T": 16, "F": 13, "A": 0, "G": 7, "H": 8, "E": 6, "L": 10,
        "R": 1, "W": 17, "V": 19, "N": 2, "Y": 18, "M": 12, "X": 20,
    }

    def __init__(self, accessions, sequences, annot_matrix, acc2idx,
                 structure_dir, prottrans_dir, esm2_dir, dssp_dir,
                 top_k=30, num_pos_emb=16, num_rbf=16):
        super().__init__()
        self.accessions = accessions
        self.sequences = sequences
        self.annot_matrix = annot_matrix
        self.acc2idx = acc2idx
        self.structure_dir = structure_dir
        self.prottrans_dir = prottrans_dir
        self.esm2_dir = esm2_dir
        self.dssp_dir = dssp_dir
        self.top_k = top_k
        self.num_pos_emb = num_pos_emb
        self.num_rbf = num_rbf

    def __len__(self):
        return len(self.accessions)

    def __getitem__(self, idx):
        name = self.accessions[idx]
        seq = self.sequences.get(name, "X" * 10)

        with torch.no_grad():
            # Load structure coordinates
            coords = np.load(
                os.path.join(self.structure_dir, f"{name}.npy"), allow_pickle=True
            )
            coords = torch.as_tensor(coords, dtype=torch.float32)

            # Sequence encoding
            seq_enc = torch.tensor(
                [self.LETTER_TO_NUM.get(aa, 20) for aa in seq], dtype=torch.long
            )

            # Use the minimum length across features
            L = min(len(coords), len(seq_enc))
            coords = coords[:L]
            seq_enc = seq_enc[:L]

            # Alpha carbon coordinates
            X_ca = coords[:, 1]  # CA atoms

            # Build k-NN graph
            k = min(self.top_k, L - 1) if L > 1 else 1
            edge_index = torch_cluster.knn_graph(X_ca, k=k)

            # Edge features
            pos_emb = self._positional_embeddings(edge_index)
            E_vectors = X_ca[edge_index[0]] - X_ca[edge_index[1]]
            rbf = _rbf(E_vectors.norm(dim=-1), D_count=self.num_rbf)
            edge_s = torch.cat([rbf, pos_emb], dim=-1)
            edge_v = _normalize(E_vectors).unsqueeze(-2)

            # Node features
            dihedrals = self._dihedrals(coords)[:L]

            prottrans = torch.tensor(
                np.load(os.path.join(self.prottrans_dir, f"{name}.npy"),
                        allow_pickle=True), dtype=torch.float32
            )[:L]
            esm2 = torch.tensor(
                np.load(os.path.join(self.esm2_dir, f"{name}.npy"),
                        allow_pickle=True), dtype=torch.float32
            )[:L]
            dssp = torch.tensor(
                np.load(os.path.join(self.dssp_dir, f"{name}_dssp.npy"),
                        allow_pickle=True), dtype=torch.float32
            )[:L]

            node_s = torch.cat([dihedrals, prottrans, esm2, dssp], dim=-1)

            # Node vector features (orientations + sidechains)
            orientations = self._orientations(X_ca)
            sidechains = self._sidechains(coords)
            node_v = torch.cat(
                [orientations, sidechains.unsqueeze(-2)], dim=-2
            )

            # Replace NaNs
            node_s, node_v, edge_s, edge_v = map(
                torch.nan_to_num, (node_s, node_v, edge_s, edge_v)
            )

            # Labels
            y = torch.tensor(
                self.annot_matrix[self.acc2idx[name]], dtype=torch.float32
            )

        return torch_geometric.data.Data(
            x=X_ca, seq=seq_enc, name=name,
            node_s=node_s, node_v=node_v,
            edge_s=edge_s, edge_v=edge_v,
            edge_index=edge_index,
            y=y,
        )

    def _dihedrals(self, X, eps=1e-7):
        X_flat = torch.reshape(X[:, :3], [3 * X.shape[0], 3])
        dX = X_flat[1:] - X_flat[:-1]
        U = _normalize(dX, dim=-1)
        u_2, u_1, u_0 = U[:-2], U[1:-1], U[2:]
        n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)
        n_1 = _normalize(torch.cross(u_1, u_0), dim=-1)
        cosD = torch.clamp(torch.sum(n_2 * n_1, -1), -1 + eps, 1 - eps)
        D = torch.sign(torch.sum(u_2 * n_1, -1)) * torch.acos(cosD)
        D = F.pad(D, [1, 2])
        D = torch.reshape(D, [-1, 3])
        return torch.cat([torch.cos(D), torch.sin(D)], 1)

    def _positional_embeddings(self, edge_index, period_range=[2, 1000]):
        d = edge_index[0] - edge_index[1]
        freq = torch.exp(
            torch.arange(0, self.num_pos_emb, 2, dtype=torch.float32)
            * -(np.log(10000.0) / self.num_pos_emb)
        )
        angles = d.unsqueeze(-1) * freq
        return torch.cat((torch.cos(angles), torch.sin(angles)), -1)

    def _orientations(self, X):
        forward = _normalize(X[1:] - X[:-1])
        backward = _normalize(X[:-1] - X[1:])
        forward = F.pad(forward, [0, 0, 0, 1])
        backward = F.pad(backward, [0, 0, 1, 0])
        return torch.cat([forward.unsqueeze(-2), backward.unsqueeze(-2)], -2)

    def _sidechains(self, X):
        n, origin, c = X[:, 0], X[:, 1], X[:, 2]
        c_norm, n_norm = _normalize(c - origin), _normalize(n - origin)
        bisector = _normalize(c_norm + n_norm)
        perp = _normalize(torch.cross(c_norm, n_norm))
        return -bisector * math.sqrt(1/3) - perp * math.sqrt(2/3)

print("✅ CAFA5ProteinGraphDataset defined")

✅ CAFA5ProteinGraphDataset defined


In [36]:
# ============================================================
# Create datasets and dataloaders
# ============================================================

from torch_geometric.loader import DataLoader

train_dataset = CAFA5ProteinGraphDataset(
    accessions=train_accessions,
    sequences=protein_sequences,
    annot_matrix=ANNOT_MATRIX,
    acc2idx=ACC2IDX,
    structure_dir=STRUCTURE_DIR,
    prottrans_dir=PROTTRANS_DIR,
    esm2_dir=ESM2_DIR,
    dssp_dir=DSSP_DIR,
    top_k=30,
)

val_dataset = CAFA5ProteinGraphDataset(
    accessions=val_accessions,
    sequences=protein_sequences,
    annot_matrix=ANNOT_MATRIX,
    acc2idx=ACC2IDX,
    structure_dir=STRUCTURE_DIR,
    prottrans_dir=PROTTRANS_DIR,
    esm2_dir=ESM2_DIR,
    dssp_dir=DSSP_DIR,
    top_k=30,
)

train_loader = DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True,
    drop_last=False, num_workers=2, prefetch_factor=2,
)
val_loader = DataLoader(
    val_dataset, batch_size=BATCH_SIZE, shuffle=False,
    drop_last=False, num_workers=2, prefetch_factor=2,
)

print(f"Train dataset: {len(train_dataset)} proteins")
print(f"Val dataset:   {len(val_dataset)} proteins")

# Test a single batch
sample = next(iter(train_loader))
print(f"\nSample batch:")
print(f"  node_s shape: {sample.node_s.shape}")
print(f"  node_v shape: {sample.node_v.shape}")
print(f"  edge_s shape: {sample.edge_s.shape}")
print(f"  edge_v shape: {sample.edge_v.shape}")
print(f"  edge_index shape: {sample.edge_index.shape}")
print(f"  y shape: {sample.y.shape}")
print(f"  Node feature dim: {sample.node_s.shape[-1]} (expecting 2324 = 6 + 1024 + 1280 + 14)")

Train dataset: 20 proteins
Val dataset:   10 proteins


/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)



Sample batch:
  node_s shape: torch.Size([11627, 2324])
  node_v shape: torch.Size([11627, 3, 3])
  edge_s shape: torch.Size([348810, 32])
  edge_v shape: torch.Size([348810, 1, 3])
  edge_index shape: torch.Size([2, 348810])
  y shape: torch.Size([425700])
  Node feature dim: 2324 (expecting 2324 = 6 + 1024 + 1280 + 14)


## 6. Embedding generation

We import the pretrained GGN-GO model directly from the cloned repository.

The model uses:
- **GVP encoder**: processes protein structure graphs with 3 GVP convolution layers
- **GraphMultisetTransformer pooling**: converts residue/node features into one protein-level representation
- **MLP readout**: maps the pooled representation to GO-term predictions

For embeddings, we extract the **512-dimensional protein-level vector from the pooling output**, before the task-specific readout head. This avoids using the later `512 → 1024 → GO logits` classifier layers, which are more tied to the original GO prediction task.

Input node features use 2324 scalar dimensions plus vector features.

In [ ]:
# ============================================================
# GGN-GO 512-dim protein embedding extractor
# ============================================================

import os
import sys
import numpy as np
import torch

sys.path.append("GGN-GO/Script")
sys.path.append("/content")

from model import GGN_GO


TASK_TO_OUT_DIM = {
    "bp": 1943,
    "mf": 489,
    "cc": 320,
}


def load_pretrained_ggngo(task, device, pooling="MTP"):
    task = task.lower()
    assert task in TASK_TO_OUT_DIM

    model = GGN_GO(
        input_dim=2324,
        hidden_dim=512,
        num_layers=3,
        augment_eps=0.95,
        dropout=0.2,
        out_dim=TASK_TO_OUT_DIM[task],
        pooling=pooling,
        pertub=False,
    ).to(device)

    ckpt_path = f"GGN-GO/Model/model_{task}.pt"
    model.load_state_dict(torch.load(ckpt_path, map_location=device))
    model.eval()

    print(f"Loaded {ckpt_path}")
    return model


def get_batch_ids(batch, id_key="name"):
    ids = getattr(batch, id_key)
    if isinstance(ids, torch.Tensor):
        ids = ids.detach().cpu().tolist()
    return [str(x) for x in ids]


@torch.no_grad()
def collect_512_embeddings(model, loader, device, id_key="name"):
    model.eval()

    captured = {}

    def hook_pool(module, inputs, output):
        captured["emb"] = output.detach()

    handle = model.pool.register_forward_hook(hook_pool)

    xs = []
    ids_all = []

    for batch in loader:
        batch = batch.to(device)

        h_V = (batch.node_s, batch.node_v)
        h_E = (batch.edge_s, batch.edge_v)

        captured.clear()
        _ = model(h_V, batch.edge_index, h_E, batch.seq, batch.batch)

        emb = captured["emb"]

        assert emb.ndim == 2, emb.shape
        assert emb.shape[1] == 512, emb.shape

        ids = get_batch_ids(batch, id_key)
        assert emb.shape[0] == len(ids), (emb.shape, len(ids))

        xs.append(emb.cpu().numpy().astype(np.float32))
        ids_all.extend(ids)

    handle.remove()

    return np.concatenate(xs, axis=0), np.asarray(ids_all, dtype=object)


def save_ggngo_512_npz(
    task,
    train_loader,
    val_loader,
    output_dir="/content/ggngo_embeddings",
    device=None,
    pooling="MTP",
    id_key="name",
):
    os.makedirs(output_dir, exist_ok=True)

    device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
    task = task.lower()

    model = load_pretrained_ggngo(task, device, pooling=pooling)

    x_train, train_ids = collect_512_embeddings(model, train_loader, device, id_key)
    x_val, val_ids = collect_512_embeddings(model, val_loader, device, id_key)

    train_path = os.path.join(output_dir, f"{task}_train_ggngo_embeddings.npz")
    val_path = os.path.join(output_dir, f"{task}_val_ggngo_embeddings.npz")

    np.savez_compressed(train_path, embeddings=x_train, ids=train_ids)
    np.savez_compressed(val_path, embeddings=x_val, ids=val_ids)

    print("Saved:")
    print(train_path, x_train.shape)
    print(val_path, x_val.shape)

    return train_path, val_path

In [45]:
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

for task in ["bp", "mf", "cc"]:
    print(f"\nGenerating embeddings for {task}...")
    save_ggngo_512_npz(
        task=task,
        train_loader=train_loader,
        val_loader=val_loader,
        output_dir="/content/ggngo_embeddings1",
        device=DEVICE,
        pooling="MTP",
        id_key="name",
    )


Generating embeddings for bp...
Loaded GGN-GO/Model/model_bp.pt


/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)
/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)


Saved:
/content/ggngo_embeddings1/bp_train_ggngo_embeddings.npz (20, 512)
/content/ggngo_embeddings1/bp_val_ggngo_embeddings.npz (10, 512)

Generating embeddings for mf...
Loaded GGN-GO/Model/model_mf.pt


/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)
/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)


Saved:
/content/ggngo_embeddings1/mf_train_ggngo_embeddings.npz (20, 512)
/content/ggngo_embeddings1/mf_val_ggngo_embeddings.npz (10, 512)

Generating embeddings for cc...
Loaded GGN-GO/Model/model_cc.pt


/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)
/tmp/ipykernel_5212/1761709890.py:137: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  n_2 = _normalize(torch.cross(u_2, u_1), dim=-1)


Saved:
/content/ggngo_embeddings1/cc_train_ggngo_embeddings.npz (20, 512)
/content/ggngo_embeddings1/cc_val_ggngo_embeddings.npz (10, 512)


In [ ]:
# Now we save this embeddings folder to GBucket for the full dataset 
# (when we did it for the full dataset) - its name
# gs://protein_shards/short_train_and_real_val_ggngo_embeddings.tar